# Generated by Django 2.0.4 on 2018-04-12 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='service',
            field=models.IntegerField(),
        ),
    ]
