# Generated by Django 2.0.4 on 2018-05-12 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('android_api', '0005_auto_20180509_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doc',
            old_name='docid',
            new_name='spec',
        ),
    ]
