# Generated by Django 2.0.4 on 2018-05-12 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('android_api', '0006_auto_20180512_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doc',
            old_name='spec',
            new_name='docid',
        ),
    ]
