# Generated by Django 2.0.4 on 2018-05-13 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('android_api', '0007_auto_20180512_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocPatient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doctor', models.CharField(max_length=40)),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='android_api.Sensor_Data')),
            ],
        ),
        migrations.CreateModel(
            name='DocResquestNoti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=40)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='android_api.User_Info')),
            ],
        ),
    ]
