# Generated by Django 2.0.4 on 2018-05-14 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('android_api', '0008_docpatient_docresquestnoti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docpatient',
            name='Doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='android_api.User_Info'),
        ),
    ]
