# Generated by Django 2.0.4 on 2018-05-14 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('android_api', '0009_auto_20180514_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docresquestnoti',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DOCTOR', to='android_api.User_Info'),
        ),
        migrations.AlterField(
            model_name='docresquestnoti',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PATIENT', to='android_api.User_Info'),
        ),
    ]
