# Generated by Django 2.0.4 on 2018-05-15 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('android_api', '0011_auto_20180516_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docpatient',
            name='Patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hello', to='android_api.Sensor_Data'),
        ),
    ]
