# Generated by Django 2.0.4 on 2018-05-16 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('android_api', '0014_auto_20180516_0353'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocPatAck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='android_api.User_Info')),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='power', to='android_api.User_Info')),
            ],
        ),
    ]
