# Generated by Django 2.0.4 on 2018-05-17 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('android_api', '0015_docpatack'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyAct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='android_api.User_Info')),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time', to='android_api.User_Info')),
            ],
        ),
        migrations.AlterField(
            model_name='docpatack',
            name='Patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space', to='android_api.User_Info'),
        ),
        migrations.AlterField(
            model_name='docpatient',
            name='Patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soul', to='android_api.User_Info'),
        ),
    ]
